- name: install nginx
  become: yes
  yum:
    name: nginx
    state: present

- name: change port
  become: yes
  template:
    src: nginx.conf
    dest: /etc/nginx/conf.d/default.conf
  register: confFileStatus

- name: start nginx
  become: yes
  service:
   name: nginx
   state: started
   enabled: yes

- name: Restart nginx
  become: yes
  service:
    name: nginx
    state: restarted
  when: confFileStatus.changed
