---
- hosts: webservers
  vars_files:
   - ./config/webservers.yml

  roles:
    - nodejs
    - nginx

- hosts: anotherWebserver
  vars_files:
    - ./config/anotherWebservers.yml
  roles:
    - nodejs
