---
- hosts: webservers
  vars_files:
   - ./vars/webservers_config.yml
  roles:
    - nodejs
    - nginx

- hosts: anotherWebserver
  vars_files:
    - ./vars/anotherWebservers_config.yml
  roles:
    - nodejs
