---
- hosts: webservers
  vars_files:
   - ./vars/webservers_config.yml
  vars:
    node_version: 7.8.0
  tasks:
   - name: Include nodejs role
     include_role:
       name: nodejs

   - name: Include nginx role
     include_role:
       name: nginx

- hosts: anotherWebserver
  vars_files:
    - ./vars/anotherWebservers_config.yml
  tasks:
    - name: Include nodejs role
      include_role:
        name: nodejs
